#!/bin/bash

##
##
## Introduction
## ============
##
## It is a shell script. The purpose of this script is to clean the current
## directory and remove useless files generated by the atompaw code.
##
## This script should be used by the developer only.
##
## Usage
## =====
##
## ./clean.sh
##
## Author
## ======
##
## This shell script is designed, created, and maintained by
##
## Li Huang // email: lihuang.dmft@gmail.com
##
## History
## =======
##
## 07/14/2019 by li huang (created)
## 07/14/2019 by li huang (last modified)
##
##

rm -fr w* t* l* pot* r* *.xml *.abinit *.pdf expot dummy density vloc NC OCCWFN
rm -fr Fr Ra Ac Th Pa U Np Pu Am Cm Bk Cf Es Fm Md No Lr Rf
